# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.

  # Directory with the serverless Lambda functions to deploy to AWS.
  functions = "src/"

[dev]

#  command = "yarn dev"
